version: 2
jobs:
  build:
    docker:
      - image: "microsoft/dotnet:2.1-sdk"
    steps:
      - checkout
      - run: echo "Sir, checkout completed."
      - run: dotnet publish --configuration=Release
